### PR TITLE
Fix Windows UI Issues

### LINKED ISSUE #60: Windows Styling Issues
### TODO
- [x] Remove toolbar for dragging when not on Mac
- [x] Remove extra width causing the scroll bar to appear
- [x] Cleanup helper shortcuts
- [x] Get Squirell Installation GIF

### PR DESCRIPTION
**Pull request by srinjoym**
Fixes #60 

### Updates
- Move to custom menu generation for app so we don't have extraneous options
- Temporary installation GIF
- Small UI tweaks with `container-fluid`

### CODE REVIEW

File: app/menu.js [hunk 1]
```diff
@@ -0,0 +1,95 @@
...
+      {role: "minimize"},
+      {role: "close"}
+    ]
+  },
+  {
+    role: "help",
+    submenu: [
+      {
+        label: "Learn More",
+        click () { require("electron").shell.openExternal("https://www.classroom.github.com/assistant") }
```
Comment (damaneice) [inline app/menu.js]: Does Classroom run locally?  It may be good to allow the host to be configurable. i.e.  `classroom.localhost`/assistant

File: app/routes/archive/components/ItemArchivePanel.jsx [hunk 2]
```diff
@@ -17,7 +17,7 @@ const ItemArchivePanel = ({
 }) => {
   let progressElement
 
-  if (cloneProgress === 0) {
+  if (cloneProgress === 0 && !cloneStatus) {
```
Comment (damaneice) [inline app/routes/archive/components/ItemArchivePanel.jsx]: What is `cloneStatus`?

File: app/routes/shared/components/Header.jsx [hunk 3]
```diff
@@ -9,7 +9,8 @@ const Header = ({
   return (
     <div>
       <div className="fixed-top shared-header-navbar">
-        <div className="shared-header-toolbar"/>
+        {process.platform === "darwin" && <div className="shared-header-toolbar"/>}
```
Comment (damaneice) [inline app/routes/shared/components/Header.jsx]: Is this only shown on Mac?

File: app/routes/archive/components/ItemArchivePanel.jsx (hunk 2 above)
Comment (srinjoym) [reply app/routes/archive/components/ItemArchivePanel.jsx]: `cloneStatus` is any message we dispatch to the store to show for the submission being cloned

Example: If a clone fails we dispatch the `cloneStatus` of a submission to be "Clone failed, an error has occurred"

There was a bug here where we were showing the spinner even after the folder had errored when cloning (noticed on Windows)

File: app/menu.js (hunk 1 above)
Comment (srinjoym) [reply app/menu.js]: Yes, Classroom does run locally, but for now, I have pointed everything in the app to point towards `www.classroom.github.com` in production since we need to know if we're in localhost vs. production when we're fetching data from the Classroom API as well.

I presume a good solution for this would be something like setting an env variable towards a certain host when running locally vs. production in the future?
