### PR TITLE
Fixes for Windows squirell updates + protocol handling

### LINKED ISSUE #54: Fix Windows Auth Window Issues
Currently the deep link protocol handler opens a whole new app window in Windows. Update functionality to match Mac.

### PR DESCRIPTION
**Pull request by srinjoym**
Fixes #54 

### Things in this PR:
- Handle squirrel events on startup
- Fix protocol handling on windows

### CODE REVIEW

File: app/main.js [hunk 1]
```diff
@@ -14,11 +14,11 @@ let loadOnReady = null
 
 const DEFAULT_PROTOCOL_HANDLER = "x-github-classroom"
 
-if (require("electron-squirrel-startup")) app.quit()
+if (require("electron-squirrel-startup")) app.exit()
```
Comment (damaneice) [inline app/main.js]: What is the difference between quit and exit?

File: app/main.js [hunk 2]
```diff
@@ -88,7 +109,9 @@ app.on("open-url", async function (event, urlToOpen) {
 })
 
 app.on("ready", async () => {
-  app.setAsDefaultProtocolClient(DEFAULT_PROTOCOL_HANDLER)
+  const anotherInstanceRunning = setInstanceProtocolHandler()
+  if (anotherInstanceRunning) app.quit()
```
Comment (damaneice) [inline app/main.js]: Should this be quit or exit?
